<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends EntityRepository
{
    /**
     * @param $id
     * @return mixed
     */
    public function getBasket($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT b.id, b.date, b.totalPrice, b.totalTTC, b.totalTVA, b.mail
            FROM AppBundle\Entity\Basket b
            WHERE b.id = :id')
            ->setParameter('id', $id);

        return $query->execute();
    }
}
