<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends EntityRepository
{
    /**
     * @param $id
     * @return mixed
     */
    public function getBillets($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT b.id, b.name, b.firstname, b.price
            FROM AppBundle\Entity\Billet b
            WHERE b.Basket = :id')
            ->setParameter('id', $id);

        return $query->execute();
    }

    /**
     * @param $id
     * @return mixed
     */
    public function getNames($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT b.name
            FROM AppBundle\Entity\Billet b
            WHERE b.Basket = :id')
            ->setParameter('id', $id);

        return $query->execute();
    }

    /**
     * @param \DateTime $dateresa
     * @return mixed
     */
    public function getBilletsDate($dateresa)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT count(b.id)
            FROM AppBundle\Entity\Billet b, AppBundle\Entity\Basket ba
            WHERE ba.id = b.Basket
            AND ba.date = :date')
            ->setParameter('date', $dateresa);

        return $query->execute();
    }





}
